-- CRIANDO BANCO E TABELAS --
CREATE DATABASE LOJA;
USE LOJA;

CREATE TABLE VENDEDOR(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(20),
    SALARIO DOUBLE,
    VENDAS INT);
    
CREATE TABLE VENDAS(
	CODIGO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NUM_ITENS INT,
    DATA_VENDA DATE,
    VALOR_TOTAL DOUBLE,
    VENDEDOR INT);
    
-- ADICIONANDO CHAVES ESTRANGEIRAS --
ALTER TABLE VENDEDOR ADD CONSTRAINT FK_VENDAS FOREIGN KEY (VENDAS)
REFERENCES VENDAS(CODIGO);

ALTER TABLE VENDAS ADD CONSTRAINT FK_VENDEDOR FOREIGN KEY (VENDEDOR)
REFERENCES VENDEDOR(ID);

-- REGISTRANDO DADOS --
INSERT INTO VENDEDOR (NOME, SALARIO) 
VALUES ('MARIA JULIA', 1350.00);
INSERT INTO VENDEDOR (NOME, SALARIO)
VALUES ('JOAO FELIPE', 1250.00);

INSERT INTO VENDAS (NUM_ITENS, DATA_VENDA, VALOR_TOTAL, VENDEDOR)
VALUES (2, '2022-10-03', 250.00, 2);
INSERT INTO VENDAS (NUM_ITENS, DATA_VENDA, VALOR_TOTAL, VENDEDOR)
VALUES (3, '2022-10-05', 400.00, 1);

SELECT * FROM VENDAS;
SELECT * FROM VENDEDOR;

-- JOINS --
SELECT CODIGO, NUM_ITENS, VENDEDOR.NOME AS VENDEDOR 
FROM VENDAS INNER JOIN VENDEDOR
ON (VENDAS.VENDEDOR = VENDEDOR.ID);

SELECT CODIGO, NUM_ITENS, VENDEDOR.NOME AS VENDEDOR 
FROM VENDAS LEFT JOIN VENDEDOR
ON (VENDAS.VENDEDOR = VENDEDOR.ID);

SELECT CODIGO, NUM_ITENS, VENDEDOR.NOME AS VENDEDOR, VALOR_TOTAL 
FROM VENDAS RIGHT JOIN VENDEDOR
ON (VENDAS.VENDEDOR = VENDEDOR.ID);

SELECT * FROM VENDAS FULL JOIN VENDEDOR;
